### ISSUE TITLE
Error happens when Zoom in or out.

### ISSUE THREAD

**Issue by LLin233** [blackfizz/EazeGraph#57]
Hey there,

I met a problem when I try to zoom out the chart. Seems I did not pass the touch event correctly.
How do I pass value to mFocusedPoint so that I can solve this error...the action was 2 fingers zooming out

java.lang.NullPointerException
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at org.eazegraph.lib.charts.ValueLineChart.calculateValueTextHeight(ValueLineChart.java:980)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at org.eazegraph.lib.charts.ValueLineChart.access$800(ValueLineChart.java:57)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at org.eazegraph.lib.charts.ValueLineChart$4.onScale(ValueLineChart.java:1050)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ScaleGestureDetector.onTouchEvent(ScaleGestureDetector.java:437)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at org.eazegraph.lib.charts.ValueLineChart.onGraphOverlayTouchEvent(ValueLineChart.java:1331)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at org.eazegraph.lib.charts.BaseChart$GraphOverlay.onTouchEvent(BaseChart.java:497)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.View.dispatchTouchEvent(View.java:7713)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2329)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1568)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.app.Activity.dispatchTouchEvent(Activity.java:2458)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2277)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.View.dispatchPointerEvent(View.java:7893)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3947)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3826)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3518)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at 
android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3575)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5532)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5512)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5483)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5612)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
09-21 12:19:28.687 7458-7458/androidpath.ll.lesleepbc E/AndroidRuntime:     at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)

**Comment by LLin233** [comment]
After I hide the indicatorline....the chart can't not be zoom in-out, it will throw error shows above.
